name: Docker Build with Layer Cache

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (with layer cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false                # don’t push anywhere
          tags: python-ci-cache-demo:latest
          cache-from: type=gha       # restore cache from GitHub Actions
          cache-to: type=gha,mode=max  # save cache back to GH Actions

